# Project information
site_name: moustic
site_author: Anais Denis
site_url: 'https://github.com/AnaisDenis/moustic'
site_description: moustic
site_dir: site # When you build your site, all of the files are written to the directory assigned to the site_dir configuration option (defaults to "site")
docs_dir: doc # The directory that holds the documentation source files (the MkDocs documentation)

# Repository
repo_name: 'moustic'
repo_url: 'https://github.com/AnaisDenis/moustic'
edit_uri: edit/main/docs/ # Allow to replace edit/master/docs use by default

# Configuration
theme:
  name: material
  logo: img/MIVEGEC.png # logo top left page
  search_index_only: true
  include_search_page: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections # collapse subsections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate # remove table of content on the right side
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets:
     base_path: doc
  - attr_list
  - tables
  - toc:
      permalink: '#'

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - macros

# Customization
extra:
#  homepage:  # Page displayed when clicking the logo
  history_buttons: false
  # --- set whole scope variables ---
  #contact: surmanme.name@gmail.com
  color_table_header: "#333a99"

# page tree
nav:
    - moustic home: 
      - index.md
    - Install python:
      - install_python.md
    - Open moustic:
      - usage.md
    - Mosqui'Track:
      - mosquitrack.md
    - Mosquit'Love:
      - mosquitlove.md
    - Mosqu'Investigate:
      - mosquinvestigate.md
