# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
# Triggers the workflow on push or pull request events
on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  

  # This workflow contains a second job called "build2"
  pmosquito:
    # avoid to run twice push and PR
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- name: Checkout AGAT
      - uses: actions/checkout@v3
      # Setup which version of Python to use
      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install 
        run: pip install .
      - name: test
        run: pmosquito -h
